### ISSUE TITLE
Jupyterlab Dependency Issue

### ISSUE THREAD

**Issue by hannibal1296** [wallneradam/jupyterlab-output-auto-scroll#1]
Hi! I tried to download but it says like this:
The extension "@wallneradam/output_auto_scroll" does not yet support the current version of JupyterLab.

>=2.0.2 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/application

Could you please fix this?

Thanks!

**Comment by felipemalbergier** [comment]
I'm having the same issue.
The problem is that its asking for a version of jupyterlab that does not exist yet.
Its asking for >=2.0.2 and as of now we are in 2.0.1 
https://pypi.org/project/jupyterlab/

**Comment by andrei91ro** [comment]
Hello! Unfortunately I am also having the same problem on JupyterLab 2.0.1.
@felipemalbergier , the fact is that the extension expects an older version of Jupyter (<2.0.0). Look carefully at the dependency table, The first column is what you have as opposed to what the extension is expecting.
```
Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.0.2 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/application
>=2.0.2 <2.1.0          >=1.1.3 <2.0.0 @jupyterlab/notebook
```

**Comment by viotemp1** [comment]
Same here. Any chance to get an updated version?
Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/application
>=2.0.0 <2.1.0          >=1.1.3 <2.0.0 @jupyterlab/notebook

**Comment by wallneradam** [comment]
I've updated it to 2.0.
