### ISSUE TITLE
JupyterLab 2.1 Update Request

### ISSUE THREAD

**Issue by b4rlw** [wallneradam/jupyterlab-output-auto-scroll#3]
Hi, I'm having an issue on JupyterLab 2.1.5, the button does not appear in the toolbar, nor is a rebuild prompted by the extension manager upon installation. Tried manual rebuilds, but I expect the plugin is not supported on 2.1. Would it be possible to update?

Best regards.

**Comment by wallneradam** [comment]
It works wonderfully for me in 2.2.6 (latest). But I think it should work also in 2.1.5 and every version after 2.1.
The problem maybe with other extensions. That could break the build process. Or if you have a lot of extensions, the build may slow and memory hungry, and nodejs's default allowed memory is not enough:
I use this command to solve that:
`NODE_OPTIONS=--max-old-space-size=16384 jupyter lab build`
Run it on a terminal (command window).

**Comment by b4rlw** [comment]
Still not working for me at the moment after disabling my other extensions and rebuilding as you advise. Perhaps there's something else going on with my build though, I'll close for now and try again once Anaconda updates JupyterLab to 2.2+.
Cheers.
